# config

version: slws
http:
  - listen: 8080
    read_timeout: 5000,
    location:
      - path: "/hello"
        root: "index.html"
tcp:
  - listen: 8081
    read_timeout: 5000
udp:
  - listen: 8082